services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "4000:3000"
    volumes:
      - ./api:/usr/src/app
    command: npm run start

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "6000:5000"
    #shm_size: 128mb
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  tob:
    build:
      context: .
      dockerfile: ./docker/toB/Dockerfile
    ports:
      - "5000:4000"
    depends_on:
      - db
      - api
    volumes:
      - ./tob:/usr/src/app
      - /usr/src/app/node_modules

  toc:
    build:
      context: .
      dockerfile: ./docker/toC/Dockerfile
    ports:
      - "8000:4000"
    depends_on:
      - db
      - api
    volumes:
      - ./toc:/usr/src/app
      - /usr/src/app/node_modules

  tocs:
    build:
      context: .
      dockerfile: ./docker/toCS/Dockerfile
    ports:
      - "3000:4000"
    depends_on:
      - db
      - api
    volumes:
      - ./tocs:/usr/src/app
      - /usr/src/app/node_modules
